export const COURIER_REGISTRATION_OTP = 'COURIER_REGISTRATION_OTP' as const;

export enum COURIER_APPROVAL_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum COURIER_ONLINE_STATUS {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  BUSY = 'BUSY',
}
