version: '3.9'
networks:
  app_network:
    driver: bridge
services:
  postgresdb:
    container_name: my_courier_env_local_postgres
    build:
      context: ./courier-prisma
      dockerfile: env-local-database.Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=courier439156
      - POSTGRES_DATABASE=courier
    ports:
      - 5477:5432
    networks:
      - app_network
    volumes:
      - saved_data:/var/lib/postgresql/data
      - ./DatabaseBackup:/DatabaseBackup
    restart: always
volumes:
  saved_data:
# docker compose -p my_courier_env_local down && docker image prune -a -f  && docker builder prune -a -f && docker compose -p my_courier_env_local -f docker-compose.env.local.yaml up -d
# docker exec -it mongo_env_local_courier /bin/bash
# docker compose -p my_courier_env_local down && docker image prune -a -f  && docker builder prune -a -f
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
# mongodump   -h 0.0.0.0    --port=27017    -u admin    -p couriernkd1996     --authenticationDatabase=courier   --archive=./DatabaseBackup/env.local.courier-20251215-14h12.tar.gz
# mongorestore    -h 0.0.0.0    --port=27017    -u root   -p couriernkd1996    -d courier   --authenticationDatabase=admin       --archive=./DatabaseBackup/env.local.courier-20251214-17h46.tar.gz
# pg_dump   -h 0.0.0.0    -p 5432   -U root   -d courier    -f ./DatabaseBackup/env.local.courier-20251219-18h09.tar.gz
# psql    -U root     -p 5432     -d courier    <   ../DatabaseBackup/env.local.courier-20251214-23h40.tar.gz
# eas build --platform android --profile local_apk --local
# docker compose -p my_courier_env_local down  && docker image prune -a -f && docker builder prune -a -f && docker volume rm my_courier_env_local_saved_data
