version: '3.9'
networks:
  app_network:
    driver: bridge
services:
  nginx:
    container_name: my_courier_env_production_nginx
    ports:
      - 2400:80
    build:
      context: ./stack-frontend
      dockerfile: env-production-frontend.Dockerfile
    volumes:
      - ./nginx/env-production-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
  postgresdb:
    container_name: my_courier_env_production_postgres
    build:
      context: ./stack-backend
      dockerfile: env-production-database.Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=courier439156
      - POSTGRES_DATABASE=courier
    expose:
      - 5432
    networks:
      - app_network
    volumes:
      - saved_data:/var/lib/postgresql/data
      - ./database:/database
    restart: always
  backend:
    container_name: my_courier_env_production_backend
    build:
      context: ./stack-backend
      dockerfile: env-production-backend.Dockerfile
    ports:
      - 8181:8181
    networks:
      - app_network
volumes:
  saved_data:
# docker compose -p my_courier_env_production down && docker image prune -a -f  && docker builder prune -a -f && docker compose -p my_courier_env_production -f docker-compose.env.production.yaml up -d && docker exec my_courier_env_production_backend sh -c "npx dotenv -e .env.production prisma migrate dev && npx dotenv -e .env.production prisma generate"
# docker exec -it mongo_env_production_baoinsurtech /bin/bash
# docker compose -p my_courier_env_production down && docker image prune -a -f  && docker builder prune -a -f
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
# mongodump   -h 0.0.0.0    --port=27017    -u admin    -p baoinsurtechnkd1996     --authenticationDatabase=baoinsurtech   --archive=./DatabaseBackup/env.production.baoinsurtech-20251215-14h12.tar.gz
# mongorestore    -h 0.0.0.0    --port=27017    -u root   -p baoinsurtechnkd1996    -d baoinsurtech   --authenticationDatabase=admin       --archive=./DatabaseBackup/env.production.baoinsurtech-20251214-17h46.tar.gz
# pg_dump   -h 0.0.0.0    -p 5432   -U root   -d baoinsurtech    -f ./DatabaseBackup/env.local.baoinsurtech-20251219-18h09.tar.gz
# psql    -U root     -p 5432     -d baoinsurtech    <   ../DatabaseBackup/env.local.baoinsurtech-20251214-23h40.tar.gz
# eas build --platform android --profile production_apk --production
# docker compose -p my_courier_env_production down  && docker image prune -a -f && docker builder prune -a -f && docker volume rm my_courier_env_production_saved_data
